version: "3.2"

services:
  mariadb:
    image: mariadb:10.3
    container_name: mariadb
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./conf.d:/etc/mysql/conf.d
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      - bootakhae
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    links:
      - mariadb
    ports:
      # 8080 is the host port and 80 is the docker port
      - 83:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - PMA_PORT=3306:3306
    depends_on:
      - mariadb
    networks:
      - bootakhae
networks:
  bootakhae:
    driver: bridge
